apiVersion: v1
kind: ConfigMap
metadata:
  name: grafana-datasources
data:
  datasources.yaml: |
    apiVersion: 1
    datasources:
      - name: Prometheus
        type: prometheus
        access: proxy
        url: http://prometheus.monitoring-demo.svc:9090
        isDefault: true
        editable: true

  # Este ConfigMap define una fuente de datos para Grafana, en este caso, Prometheus.
  # Esto hace que Grafana ya arranque con Prometheus configurado.
