apiVersion: v1
kind: Secret
metadata:
  name: grafana-secret
type: Opaque
stringData:
  GF_SECURITY_ADMIN_USER: "admin"
  GF_SECURITY_ADMIN_PASSWORD: "Grafana123!"

  #Estas variables de entorno se utilizan para configurar el usuario administrador de Grafana.
  #Crea un secret con usuario y password