apiVersion: v1
kind: ServiceAccount
metadata:
  name: grafana
  # crea serviceaccount para Grafana
  # se puede usar para asignar permisos específicos a Grafana mediante RoleBinding o ClusterRoleBinding
  