apiVersion: v1
kind: ConfigMap
metadata:
  name: blackbox-config
data:
  blackbox.yml: |
    modules:
      http_2xx:
        prober: http
        timeout: 5s
        http:
          preferred_ip_protocol: "ip4"
          valid_http_versions: ["HTTP/1.1", "HTTP/2.0"]
          valid_status_codes: []
          method: GET

#Define cómo hacer las comprobaciones HTTP
#En este ejemplo, se define un módulo llamado "http_2xx" que utiliza el prober HTTP para realizar comprobaciones. El prober HTTP se configura para preferir el protocolo IPv4, aceptar versiones HTTP 1.1 y 2.0, y considerar cualquier código de estado como válido (ya que la lista de códigos de estado válidos está vacía).
# El método HTTP utilizado para las comprobaciones es GET.
