apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - serviceaccount.yaml
  - configmap.yaml
  - pvc.yaml
  - deployment.yaml
  - service.yaml
  - route.yaml

#Kustomization que agrupa todos los recursos de Prometheus. Al aplicar este kustomization, se crean el ServiceAccount, ConfigMap, PVC, Deployment, Service y Route de Prometheus.
#Kustomize qué recursos forman parte de esta app
